spring:
  application:
    name: hometask-43
  datasource:
    url: jdbc:postgresql://localhost:5432/hw-43
    username: postgres
    password: root
  jpa:
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
server:
  port: 8081