rootProject.name = "FirstProject"
include("hometask_1")
include("hometask-5")
include("hometask_2")
include("homework_7")
include("hometask_6")
include("hometask_8")
include("hometask_9")
include("hometask-11")
include("hometask-10")
include("hometask-12")
include("hometask-12")
include("hometask-14")
include("hometask-18-Streams")
