spring:
  application:
    name: hometask-42
  datasource:
    url: jdbc:postgresql://localhost:5432/hw-42
    username: postgres
    password: root
  jpa:
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true